import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import { useState } from 'react'
import RecentlyUpdatedTable from '../components/RecentlyUpdatedTable'
import SearchBar from '../components/SearchBar'

export default function Home() {
  const [ worldName, setWorldName ] = useState('Cerberus')
  return (
    <div className={styles.container}>
      <Head>
        <title>Rowena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header search={false} />
      <main>
      <div className={styles.mainContainer}>
        <div className={styles.searchContainer}>
          <div className={styles.searchBarContainer}>
            <SearchBar width={"700px"}/>
          </div>
        </div>
        <div className={styles.recentlyUpdatedContainer}>
          <h2>Recently Updated on Cerberus</h2>
          <RecentlyUpdatedTable world={worldName} refreshInterval={30}/>
        </div>
      </div>
      </main>
    </div>
  )
}
